version: "3.5"

services:

  php:
    container_name: ${M2C_CFG_DOMAIN_NAME}__php
    hostname: ${M2C_CFG_DOMAIN_NAME}__php
    image: mage2click/m2c:php-fpm-${M2C_CFG_PHP:-7.3}-alpine
    extra_hosts:
      - ${M2C_CFG_DOMAIN_NAME}:${M2C_TRAEFIK_IP:-0.0.0.0}
    depends_on:
      - db
    labels:
      - m2c.project.path=${M2C_CFG_PROJECT_PATH}
    networks:
      - default
      - m2c

  xdebug:
    container_name: ${M2C_CFG_DOMAIN_NAME}__xdebug
    hostname: ${M2C_CFG_DOMAIN_NAME}__xdebug
    image: mage2click/m2c:php-fpm-${M2C_CFG_PHP:-7.3}-xdebug-alpine
    extra_hosts:
      - ${M2C_CFG_DOMAIN_NAME}:${M2C_TRAEFIK_IP:-0.0.0.0}
    environment:
      - PHP_IDE_CONFIG=serverName=${M2C_CFG_DOMAIN_NAME}
    depends_on:
      - db
    networks:
      - default
      - m2c

  db:
    container_name: ${M2C_CFG_DOMAIN_NAME}__db
    hostname: ${M2C_CFG_DOMAIN_NAME}__db
    image: mariadb:${M2C_CFG_MARIADB:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${M2C_CFG_MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${M2C_CFG_MYSQL_DATABASE:-magento}
      - MYSQL_USER=${M2C_CFG_MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
    volumes:
      - ./../mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - db_data:/var/lib/mysql
    networks:
      - default
      - m2c

  redis:
    container_name: ${M2C_CFG_DOMAIN_NAME}__redis
    hostname: ${M2C_CFG_DOMAIN_NAME}__redis
    image: redis:${M2C_CFG_REDIS:-5.0}-alpine
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:

networks:
  m2c:
    external: true