#!/bin/bash

if [[ -z ${m2c_global_dir} ]]
then
    echo -e "\033[1;31mThis script intended to be sourced and should not be executed directly!\033[0m"
    exit 1
fi

if [[ "$m2c_os" != "darwin" ]]
then
    echo -e "\033[1;31mMutagen sync functionality is only for macOS!\033[0m"
    exit 1
fi

export MUTAGEN_DATA_DIRECTORY="$m2c_global_dir"/mutagen
"$MUTAGEN_DATA_DIRECTORY"/mutagen daemon start
"$MUTAGEN_DATA_DIRECTORY"/mutagen $@