#!/bin/bash

if [[ -z "$m2c_global_dir" ]]
then
    echo -e "\033[1;31mThis script intended to be sourced and should not be executed directly!\033[0m"
    exit 1
fi

m2c_pull() {
    local project_dir="${m2c_project_dir}" \
          sub_dir=${M2C_CFG_MAGENTO_SRC:-} \
          container_id="${M2C_CFG_DOMAIN_NAME}__php" \
          source_path error res

    m2c_info_bold "\n[Pull]\n\n"

    if [[ -n ${container_id} ]]
    then
        if [[ -z "$1" ]]
        then
            m2c_msg "Pulling files from php docker container................................  "
            m2c_loading
            m2c sync pause >/dev/null 2>&1 && \
            docker cp "$container_id":/var/www/html/. "$project_dir${sub_dir:+/${sub_dir}}/" >"$m2c_log" 2>&1 && \
            m2c sync resume >/dev/null 2>&1
            res=$?
            m2c_result ${res}
            return ${res}
        else
            source_path="${1%%+(/)}"
            dest_path="$project_dir${sub_dir:+/${sub_dir}}/$source_path"

            if m2c bash notty -c "[[ -d "/var/www/html/${source_path}" ]]" >"$m2c_log" 2>&1
            then
                m2c_info "$source_path\n"
                m2c_msg "Pulling directory from php docker container............................  "
                m2c_loading
                m2c sync pause >/dev/null 2>&1 && \
                docker cp "$container_id":/var/www/html/"$source_path"/. "$dest_path" >"$m2c_log" 2>&1 && \
                m2c sync resume >/dev/null 2>&1
                res=$?
                m2c_result ${res}
                return ${res}
            elif m2c bash notty -c "[[ -f "/var/www/html/${source_path}" ]]" >"$m2c_log" 2>&1
            then
                m2c_info "$source_path\n"
                m2c_msg "Pulling file from php docker container.................................  "
                m2c_loading
                m2c sync pause >/dev/null 2>&1 && \
                docker cp "$container_id":/var/www/html/"$source_path" "$(dirname "$dest_path")" >"$m2c_log" 2>&1 && \
                m2c sync resume >/dev/null 2>&1
                res=$?
                m2c_result ${res}
                return ${res}
            else
                error="Specified path does not exist on php docker container: \n$source_path\n\n"
            fi
        fi
    else
        error="Docker php container must be started to pull files from it!\n\n"
    fi

    if [[ -n ${error} ]]
    then
        m2c_error "$error"
    fi

    return 1
}

m2c_pull_help() {
    m2c_logo

    echo -e "
\033[1;33mInformation:\033[0m
  Pull file or directory from php docker container to Magento src root. To
  pull multiple files or directories, specify paths as list divided by spaces.
  To pull all files, use --all parameter. e.g. \`m2c pull -all\`. Specified
  paths must be relative to container's /var/www/html directory.

\033[1;33mUsage:\033[0m
  m2c pull [<path1> [<path2>...]] [flags...]

\033[1;33mFlags:\033[0m
  --all     Pull all files from php docker container to magento src root.
  --help    Display this information.
"
    exit 0
}

if (("$#"))
then
    m2c_in_array "--help" $@ && m2c_pull_help

    if m2c_in_array "--all" $@
    then
        m2c_pull
    else
        while (("$#")); do
            case "$1" in
                *)
                    m2c_pull "$1"
                ;;
            esac
            shift
        done
    fi
else
    m2c_pull_help
fi