#!/bin/bash

if [[ -z "$m2c_global_dir" ]]
then
    echo -e "\033[1;31mThis script intended to be sourced and should not be executed directly!\033[0m"
    exit 1
fi

m2c_push() {
    local project_dir="${m2c_project_dir}" \
          sub_dir=${M2C_CFG_MAGENTO_SRC:-} \
          container="${M2C_CFG_DOMAIN_NAME}__php" \
          source_path error res

    m2c_info_bold "\n[Push]\n\n"

    if [[ -n ${container} ]]
    then
        if [[ -z "$1" ]]
        then
            m2c_msg "Pushing all files to php docker container..............................  "
            m2c_loading
            m2c sync pause >/dev/null 2>&1 && \
            docker cp "$project_dir${sub_dir:+/${sub_dir}}"/. "$container":/var/www/html/ >"$m2c_log" 2>&1 && \
            docker exec "$container" chown -R app:app /var/www/ >"$m2c_log" 2>&1 && \
            docker exec "$container" chmod u+x ./bin/magento >"$m2c_log" 2>&1 && \
            docker exec "$container" chmod u+w -R ./var ./vendor ./pub/static ./pub/media ./app/etc >"$m2c_log" 2>&1 && \
            m2c sync resume >/dev/null 2>&1
            res=$?
            m2c_result ${res}
            return ${res}
        else
            dest_path="${1%%+(/)}"
            source_path="$project_dir${sub_dir:+/${sub_dir}}/$dest_path"

            if [[ -d "$source_path" || -f "$source_path" ]]
            then
                m2c_info "$source_path\n"

                if [[ -d "$source_path" ]]
                then
                    m2c_msg "Pushing directory to php docker container..............................  "
                    m2c_loading
                    m2c sync pause >/dev/null 2>&1 && \
                    docker cp "$source_path"/. "$container":/var/www/html/"$dest_path" >"$m2c_log" 2>&1 && \
                    docker exec "$container" chown -R app:app "$dest_path" >"$m2c_log" 2>&1 && \
                    case "$dest_path" in
                        var|vendor|pub/static|pub/media|app/etc|var/*|vendor/*|pub/static/*|pub/media/*|app/etc/*)
                            docker exec "$container" chmod u+w -R ./"$dest_path" >"$m2c_log" 2>&1
                        ;;
                        *)
                            true
                        ;;
                    esac && \
                    m2c sync resume >/dev/null 2>&1
                else
                    m2c_msg "Pushing file to php docker container....................................  "
                    m2c_loading
                    m2c sync pause >/dev/null 2>&1 && \
                    docker cp "$source_path" "$container":/var/www/html/"$(dirname "$dest_path")" >"$m2c_log" 2>&1 && \
                    docker exec "$container" chown -R app:app "$dest_path" >"$m2c_log" 2>&1 && \
                    case "$dest_path" in
                        bin/magento)
                            docker exec "$container" chmod u+x ./"$source_path" >"$m2c_log" 2>&1
                        ;;
                        var/*|vendor/*|pub/static/*|pub/media/*|app/etc/*)
                            docker exec "$container" chmod u+w -R ./"$dest_path" >"$m2c_log" 2>&1
                        ;;
                        *)
                            true
                        ;;
                    esac && \
                    m2c sync resume >/dev/null 2>&1
                fi

                res=$?
                m2c_result ${res}
                return ${res}
            else
                error="Specified path does not exist on host machine: \n$source_path\n\n"
            fi
        fi
    else
        error="Docker php container must be started to push files into it!\n\n"
    fi

    if [[ -n ${error} ]]
    then
        m2c_error "$error"
    fi

    return 1
}

m2c_push_help() {
    m2c_logo

    echo -e "
\033[1;33mInformation:\033[0m
  Push local file or directory from magento src root to php docker container.
  To push multiple files or directories, specify paths as list divided by
  spaces. To push all files, use --all parameter. e.g. \`m2c push -all\`.
  Specified paths must be relative to Magento src root directory.

\033[1;33mUsage:\033[0m
  m2c push [<path1> [<path2>...]] [flags...]

\033[1;33mFlags:\033[0m
  --all     Push all files from magento src root to php docker container.
  --help    Display this information.
"
    exit 0
}

if (("$#"))
then
    m2c_in_array "--help" $@ && m2c_push_help

    if m2c_in_array "--all" $@
    then
        m2c_push
    else
        while (("$#")); do
            case "$1" in
                *)
                    m2c_push "$1"
                ;;
            esac
            shift
        done
    fi
else
    m2c_push_help
fi