#!/bin/bash

if [[ -z "$m2c_global_dir" ]]
then
    echo -e "\033[1;31mThis script intended to be sourced and should not be executed directly!\033[0m"
    exit 1
fi

m2c_share_error() {
    m2c_error "Unknown argument $@. Run \`m2c share --help\` for usage information.\n"
    exit 1
}

m2c_share() {
    local region="$1"
          network="${M2C_CFG_DOMAIN_NAME/.test/}_default" \
          container="${M2C_CFG_DOMAIN_NAME}__$([[ -n ${M2C_CFG_VARNISH} ]] && echo "varnish" || echo "nginx")" \
          port="$([[ -n ${M2C_CFG_VARNISH} ]] && echo "80" || echo "8080")"

    m2c_info_bold "\n[Share]\n\n"

    m2c_msg "Checking required dependencies.........................................  "
    m2c_loading
    m2c_res="$(m2c magento notty module:status Shkoliar_Ngrok)"
    m2c_result 0

    if [[ "$m2c_res" != "Module is enabled"* ]]
    then
        m2c_msg "Installing required dependencies.......................................  "
        m2c_loading
        m2c composer notty require --dev shkoliar/magento-ngrok >"$m2c_log" 2>&1 && \
        m2c magento notty module:enable Shkoliar_Ngrok >"$m2c_log" 2>&1 && \
        m2c magento notty setup:upgrade >"$m2c_log" 2>&1
        m2c_res=$?
        m2c_result ${m2c_res}
    else
        m2c_res=0
    fi

    if [[ "$m2c_res" == "0" ]]
    then
        m2c_msg "Starting sharing session...............................................  "
        m2c_loading
        docker pull shkoliar/ngrok >"$m2c_log" 2>&1
        m2c_result ${m2c_res}

        docker run --rm -it -p 0.0.0.0:4551:4551/tcp --link ${container} --net ${network} \
                shkoliar/ngrok ngrok http -region=${region} \
                -bind-tls=true ${container}:${port} 2>"$m2c_log"
        m2c_res=$?

        if [[ "$m2c_res" == "0" ]]
        then
            m2c_msg "Sharing session ended..................................................  "
            m2c_result 0
        elif [[ -f "$m2c_log" ]]
        then
            error="$(echo $(cat "$m2c_log"))"
            [[ -n ${error} ]] && m2c_error "$error\n"
        fi
    fi

    exit ${m2c_res}
}

m2c_share_help() {
    m2c_logo

    echo -e "
\033[1;33mInformation:\033[0m
  Start share session over ngrok secure tunnels. Command accepts optional
  parameter to specify a region. Ex. \`m2c share eu\`. Available regions are
  \`us\`, \`eu\`, \`ap\`, \`au\`, \`sa\`, \`jp\`, \`in\`. By default region is \`us\`.
  For proper functioning of this command, required dependencies will be
  installed. Please, visit https://github.com/shkoliar/magento-ngrok and
  https://github.com/shkoliar/docker-ngrok for more information.

\033[1;33mUsage:\033[0m
  m2c share [region] [--help]

\033[1;33mRegions:\033[0m
  us        United States.
  eu        Europe.
  ap        Asia/Pacific.
  au        Australia.
  sa        South America.
  jp        Japan.
  in        India.

\033[1;33mFlags:\033[0m
  --help    Display this information.
"
    exit 0
}

if (("$#"))
then
    case "$@" in
        --help)
            m2c_share_help
        ;;
        us|eu|ap|au|sa|jp|in)
            m2c_share $1
        ;;
        *)
            m2c_share_error
        ;;
    esac
else
    m2c_share us
fi