#!/bin/bash

set -e

if [[ -z ${m2c_global_dir} ]]
then
    echo -e "\033[1;31mThis script intended to be sourced and should not be executed directly!\033[0m"
    exit 1
fi

if [[ -z "$@" ]]; then
    m2c_error "Please specify a varnish command. e.g. varnishstat\n"
    exit 1
fi

docker exec -i "${M2C_CFG_DOMAIN_NAME}__varnish" "$@"