#!/bin/bash

ping -q -c1 "host.docker.internal" > /dev/null 2>&1
if [[ $? -ne 0 ]]
then
  echo -e "$(ip route | awk 'NR==1 {print $3}')\thost.docker.internal" >> /etc/hosts
fi

if [[ -f /usr/share/ca-certificates/m2c/rootCA.crt ]]
then
 	cat /usr/share/ca-certificates/m2c/rootCA.crt >> /etc/ssl/cert.pem
 	cat /usr/share/ca-certificates/m2c/rootCA.crt >> /etc/ssl/certs/ca-certificates.crt
fi